import { readdir } from 'node:fs';

export default {
	async fetch() {
		const publicFiles = await new Promise(resolve => {
			readdir('/public', { withFileTypes: true }, (_, files) => {
				resolve(files);
			})
		});

		return new Response(`
			<!DOCTYPE html>
			<html lang="en">
			<head>
				<meta charset="UTF-8">
				<meta name="viewport" content="width=device-width, initial-scale=1.0">
				<title>Public Files</title>
			</head>
			<body>
				<h1>Public Files</h1>
				<p>This is HTML server side generated by the worker, reading files from the /public directory</p>
				<h2><code>readdir</code></h2>
				<p><code>readdir</code> run against <code>'/public'</code> results in: </p>
				<ul>
					${publicFiles.map(file => `<li>${file.name} (which is a ${file.isFile() ? 'file' : 'directory'})</li>`).join('')}
				</ul>
			</body>
			</html>
		`, {
			headers: { 'Content-Type': 'text/html' }
		});
	},
};
